// Copy and per-city settings, ported from the Claude Design file (Challan Site.dc.html).

export const CITIES = {
  noida: { code:'GBN', name:{en:'Noida & Greater Noida',hi:'नोएडा और ग्रेटर नोएडा'}, district:{en:'Gautam Buddha Nagar',hi:'गौतम बुद्ध नगर'},
    court:{en:'District Court, Surajpur',hi:'जिला न्यायालय, सूरजपुर'}, address:{en:'District & Sessions Court, Surajpur, Greater Noida, Uttar Pradesh 201306',hi:'जिला एवं सत्र न्यायालय, सूरजपुर, ग्रेटर नोएडा, उत्तर प्रदेश 201306'},
    plateHint:'UP16 AB 1234', date:'2026-12-12T10:00:00+05:30', mapsQ:'District Court Surajpur Greater Noida',
    booking:{en:'Reserve your spot here. We file your case, collect the token at Surajpur on the day and settle it for you. You never visit the court.',hi:'यहाँ अपनी जगह रिज़र्व करें। हम आपका केस दाख़िल करते हैं, उस दिन सूरजपुर में टोकन लेते हैं और निपटारा करते हैं। आपको कोर्ट नहीं जाना पड़ता।'},
    office:{en:'Office: Sector 63, Noida',hi:'ऑफ़िस: सेक्टर 63, नोएडा'},
    locs:{en:['Sector 62, Noida','Pari Chowk, Greater Noida','Noida–Greater Noida Expressway','Sector 18, Noida'],hi:['सेक्टर 62, नोएडा','परी चौक, ग्रेटर नोएडा','नोएडा–ग्रेटर नोएडा एक्सप्रेसवे','सेक्टर 18, नोएडा']} },
  ghaziabad: { code:'GZB', name:{en:'Ghaziabad',hi:'गाज़ियाबाद'}, district:{en:'Ghaziabad district',hi:'गाज़ियाबाद ज़िला'},
    court:{en:'District Court, Ghaziabad',hi:'जिला न्यायालय, गाज़ियाबाद'}, address:{en:'District Court Complex, Raj Nagar, Ghaziabad, Uttar Pradesh 201002',hi:'जिला न्यायालय परिसर, राज नगर, गाज़ियाबाद, उत्तर प्रदेश 201002'},
    plateHint:'UP14 AB 1234', date:'2026-12-12T10:00:00+05:30', mapsQ:'District Court Ghaziabad Raj Nagar',
    booking:{en:'Reserve your spot here. We prepare your file, attend on the day and settle it for you.',hi:'यहाँ अपनी जगह रिज़र्व करें। हम फ़ाइल तैयार करते हैं, उस दिन जाते हैं और निपटारा करते हैं।'},
    office:{en:'Office: Raj Nagar, Ghaziabad',hi:'ऑफ़िस: राज नगर, गाज़ियाबाद'},
    locs:{en:['Hapur Chungi','Raj Nagar Extension','NH-9, Vijay Nagar','Indirapuram'],hi:['हापुड़ चुंगी','राज नगर एक्सटेंशन','NH-9, विजय नगर','इंदिरापुरम']} },
  delhi: { code:'DEL', name:{en:'Delhi',hi:'दिल्ली'}, district:{en:'NCT of Delhi',hi:'राष्ट्रीय राजधानी क्षेत्र दिल्ली'},
    court:{en:'Allotted Delhi court complex',hi:'आवंटित दिल्ली कोर्ट परिसर'}, address:{en:'Court complex and time slot as per your online token',hi:'ऑनलाइन टोकन के अनुसार कोर्ट परिसर और समय'},
    plateHint:'DL3C AB 1234', date:'2026-12-12T10:00:00+05:30', mapsQ:'Delhi Lok Adalat court complex',
    booking:{en:'Reserve your spot here. We book the official slot when it opens, attend on the day and settle it for you.',hi:'यहाँ अपनी जगह रिज़र्व करें। आधिकारिक स्लॉट खुलते ही हम बुक करते हैं, उस दिन जाते हैं और निपटारा करते हैं।'},
    office:{en:'Office: Laxmi Nagar, Delhi',hi:'ऑफ़िस: लक्ष्मी नगर, दिल्ली'},
    locs:{en:['Ring Road, Lajpat Nagar','ITO Crossing','Outer Ring Road, Rohini','Connaught Place'],hi:['रिंग रोड, लाजपत नगर','ITO चौराहा','आउटर रिंग रोड, रोहिणी','कनॉट प्लेस']} },
  gurugram: { code:'GGN', name:{en:'Gurugram',hi:'गुरुग्राम'}, district:{en:'Gurugram district',hi:'गुरुग्राम ज़िला'},
    court:{en:'District Court, Gurugram',hi:'जिला न्यायालय, गुरुग्राम'}, address:{en:'District & Sessions Court, Gurugram, Haryana',hi:'जिला एवं सत्र न्यायालय, गुरुग्राम, हरियाणा'},
    plateHint:'HR26 AB 1234', date:'2026-12-12T10:00:00+05:30', mapsQ:'District Court Gurugram',
    booking:{en:'Reserve your spot here. We handle pre-registration, attend on the day and settle it for you.',hi:'यहाँ अपनी जगह रिज़र्व करें। रजिस्ट्रेशन, उस दिन जाना और निपटारा — सब हम करते हैं।'},
    office:{en:'Office: Sector 44, Gurugram',hi:'ऑफ़िस: सेक्टर 44, गुरुग्राम'},
    locs:{en:['IFFCO Chowk','Golf Course Road','NH-48, Sector 29','Sohna Road'],hi:['इफ़को चौक','गोल्फ़ कोर्स रोड','NH-48, सेक्टर 29','सोहना रोड']} },
};

export const T = {
 en: {
  heroTitle1:'Pending challans?', heroTitle2:'Settle them at Lok Adalat, without the hassle.',
  heroSub:'Reserve your Lok Adalat spot online. Our team handles the documents, the court visit and the settlement in {city} — you never have to go. Flat 50% of your challan amount.',
  plateLabel:'Your vehicle number', plateHint:'Format', plateError:'Enter a valid vehicle number, e.g. {plate}', checkBtn:'Get my challans checked',
  trust1:'Free check', trust2:'WhatsApp reply in 2 hours', trust3:'Flat 50% of challan',
  countdownLabel:'Next Lok Adalat', days:'Days', hrs:'Hrs', min:'Min', sec:'Sec', seeCarry:'How booking works',
  howEyebrow:'How it works', howTitle:'Book online. We handle the court.',
  how1t:'Share your details', how1d:'Enter your vehicle number, name and mobile number. It takes less than a minute.',
  how2t:'We check your challans', how2d:'Our team pulls every pending e-challan on your vehicle and confirms which ones the Lok Adalat can take up.',
  how3t:'Reserve your spot', how3d:'Book your slot for the next Lok Adalat right here, then share your RC and ID on WhatsApp.',
  how4t:'We settle it for you', how4d:'Our team attends {court} on Lok Adalat day on your behalf. You get the receipt on WhatsApp.',
  whyEyebrow:'Why {brand}', whyTitle:'For people who would rather not lose a whole day at court',
  why1t:'Assisted documentation', why1d:'Forms, challan printouts and authorisation letters — prepared and checked for you.',
  why2t:'WhatsApp updates', why2d:'Status, reminders and what to carry, straight to WhatsApp. No app to install.',
  why3t:'Local team at the court', why3d:'People on the ground at {court} who attend on your behalf — you skip the court day entirely.',
  why4t:'Flat 50% pricing', why4d:'You pay 50% of your challan amount. One price, shown before you book — no hidden charges.',
  nextEyebrow:'Next Lok Adalat', nextTitle:'Next Lok Adalat for {city}', moreDates:'More upcoming dates',
  venue:'Venue', reporting:'Your presence', reportingVal:'Not required', bookingTitle:'How it works at this court',
  carryTitle:'What we need from you — on WhatsApp', carry:['Photo of vehicle RC','Photo of driving licence','Photo ID — Aadhaar or PAN','Signed authorisation letter (we prepare it, you just sign)'],
  addCal:'Add to calendar', reserveBtn:'Reserve my spot', youPay:'You pay (flat 50%)', directions:'Directions',
  faqEyebrow:'FAQs', faqTitle:'Questions people ask us',
  faqs:[
   {q:'Which challans are eligible?', a:'Most compoundable traffic offences — over-speeding, red-light jumping, no helmet or seatbelt, wrong parking, documents not carried — are usually taken up. Serious offences like drunk driving, accident-related cases and challans already sent to regular court are usually not. We confirm eligibility for each challan before you commit.'},
   {q:'Is Lok Adalat settlement final?', a:'Yes. A Lok Adalat award is final and binding, and no appeal lies against it. Once you pay the settled amount, the challan is marked disposed.'},
   {q:'Do I need to be present?', a:'No. Once you reserve your spot, our team attends the Lok Adalat on your behalf using a signed authorisation letter. We prepare the letter — you just sign it and share it on WhatsApp.'},
   {q:'What are your fees?', a:'A flat 50% of your challan amount. Checking challans is free, and you see the exact price before you book. Nothing is charged until we confirm your challans are eligible.'},
   {q:'Are you a government website?', a:'No. {brand} is a private facilitation service. We are not affiliated with any government department, court, or police authority. You are free to approach the Lok Adalat directly on your own.'},
  ],
  disclaimerTitle:'Disclaimer', disclaimer:'We are a private facilitation service and are not affiliated with any government department, court, or police authority.',
  privacy:'Privacy policy', terms:'Terms of service', contact:'Contact', waFab:'WhatsApp',
  stepVerify:'Verify', stepResults:'Challans', stepDetails:'Book',
  phoneTitle:'Verify your mobile number', phoneDesc:"We'll send a 6-digit OTP. Challan details are shown only after verification.", phoneLabel:'Mobile number', sendOtp:'Send OTP', phoneErr:'Enter a valid 10-digit mobile number', lookupConsent:'By continuing, you allow us to look up e-challan records for this vehicle.',
  otpTitle:'Enter the 6-digit OTP', otpDesc:'Sent to {phone}', change:'Change', resendIn:'Resend OTP in {s}s', resend:'Resend OTP', verifyBtn:'Verify & fetch challans', otpDemo:'Demo mode: any 6 digits', otpErr:'That OTP is incorrect or expired. Try again.', netErr:'Something went wrong. Please try again.', tooMany:'Too many attempts. Please wait a few minutes.',
  loadingTitle:'Fetching challans…', loadingDesc:'Checking e-challan records for {plate}',
  totalPending:'Total pending', challansFound:'{n} challans found', eligibleSum:'{n} likely eligible · {amt}', benchNote:'Eligibility shown is indicative. We confirm each challan before your booking is final.',
  tagEligible:'Likely eligible for Lok Adalat', tagNot:'Not eligible', tagPaid:'Already paid / disposed', settleCta:'Reserve my Lok Adalat spot',
  emptyTitle:'No pending challans found 🎉', emptyDesc:'{plate} has no pending e-challans as of today.', alertTitle:'Get alerts for future challans', alertDesc:"We'll WhatsApp you if a new challan shows up on this vehicle. Free.", alertBtn:'Turn on WhatsApp alerts', checkAnother:'Check another vehicle',
  errTitle:"We couldn't reach the challan records right now", errDesc:"Don't worry — leave your details and we'll check manually and call you.",
  formTitle:'Reserve your Lok Adalat spot', formTitleErr:"We'll check manually and call you", formSum:'{n} eligible challans ({amt}) · You pay {fee}',
  fVehicle:'Vehicle number', fPhone:'Mobile number', verified:'Verified', fName:'Full name', fNamePh:'As on your RC', fEmail:'Email', optional:'(optional)', fType:'Vehicle type', car:'Car', bike:'2-wheeler', commercial:'Commercial',
  consent:'I agree to {brand} using these details to process my request and sending me updates on WhatsApp.', submit:'Get my challans checked', feeNote:'No payment now. You pay {fee} only after we confirm eligibility. No court visit needed.',
  thanksTitle:'Request received', thanksAlertTitle:'Challan alerts are on', refLabel:'Reference number', thanksWa:"We'll WhatsApp you within 2 hours.", thanksAlertWa:"We'll WhatsApp you if a new challan appears.",
  nextTitle2:'What happens next', next1:'An advisor checks your e-challans and tells you which are eligible and the final price', next2:'If you go ahead, share RC, ID and a signed authorisation on WhatsApp', next3:'Our team settles it on {date} — receipt on WhatsApp',
  leadTitle:'Get your challans checked', leadDesc:'Leave your details. Our team checks every pending e-challan on this vehicle and contacts you on WhatsApp with the eligible amount and price.', leadNote:'Free. No payment now. You pay 50% of the challan amount only if you decide to go ahead.', dateTba:'Date to be announced', dateTbaInline:'the next Lok Adalat day', dateTbaDesc:'Reserve now and we will WhatsApp you as soon as the date is out.', waNow:'Chat on WhatsApp now', backHome:'Back to home',
  reasonSerious:'Serious offence — handled by regular court, not Lok Adalat. We can still advise you.', reasonCourt:'Already sent to regular court — usually not taken up at Lok Adalat. We can still advise you.',
  sampleData:'Sample data · live challan API not connected yet',
 },
 hi: {
  heroTitle1:'चालान पेंडिंग हैं?', heroTitle2:'लोक अदालत में निपटाएँ, बिना झंझट के।',
  heroSub:'लोक अदालत में अपनी जगह ऑनलाइन रिज़र्व करें। दस्तावेज़, कोर्ट जाना और निपटारा — {city} में सब हमारी टीम करती है, आपको जाना नहीं पड़ता। चालान राशि का सिर्फ़ 50%।',
  plateLabel:'आपका वाहन नंबर', plateHint:'फ़ॉर्मेट', plateError:'सही वाहन नंबर डालें, जैसे {plate}', checkBtn:'मेरे चालान जाँचें',
  trust1:'मुफ़्त जाँच', trust2:'2 घंटे में WhatsApp जवाब', trust3:'चालान का सिर्फ़ 50%',
  countdownLabel:'अगली लोक अदालत', days:'दिन', hrs:'घंटे', min:'मिनट', sec:'सेकंड', seeCarry:'बुकिंग कैसे होती है',
  howEyebrow:'कैसे काम करता है', howTitle:'ऑनलाइन बुक करें। कोर्ट हम संभालेंगे।',
  how1t:'अपना विवरण दें', how1d:'वाहन नंबर, नाम और मोबाइल नंबर डालें। एक मिनट से भी कम लगता है।',
  how2t:'हम चालान जाँचते हैं', how2d:'हमारी टीम आपके वाहन के सभी पेंडिंग ई-चालान निकालकर बताती है कि कौन-से लोक अदालत में लिए जा सकते हैं।',
  how3t:'अपनी जगह रिज़र्व करें', how3d:'यहीं अगली लोक अदालत के लिए स्लॉट बुक करें, फिर RC और ID WhatsApp पर भेजें।',
  how4t:'निपटारा हम करते हैं', how4d:'लोक अदालत के दिन हमारी टीम आपकी ओर से {court} जाती है। रसीद आपको WhatsApp पर मिलती है।',
  whyEyebrow:'{brand} क्यों', whyTitle:'उनके लिए जो कोर्ट में पूरा दिन नहीं गँवाना चाहते',
  why1t:'दस्तावेज़ों में मदद', why1d:'फ़ॉर्म, चालान प्रिंटआउट और अधिकार-पत्र — सब तैयार और जाँचे हुए।',
  why2t:'WhatsApp अपडेट', why2d:'स्टेटस, रिमाइंडर और क्या साथ लाना है — सीधे WhatsApp पर। कोई ऐप नहीं।',
  why3t:'कोर्ट पर लोकल टीम', why3d:'{court} में मौजूद लोग, जो आपकी ओर से जाते हैं — आपको कोर्ट जाने की ज़रूरत नहीं।',
  why4t:'फ़्लैट 50% क़ीमत', why4d:'आप चालान राशि का 50% देते हैं। एक ही क़ीमत, बुकिंग से पहले दिखाई जाती है — कोई छिपा शुल्क नहीं।',
  nextEyebrow:'अगली लोक अदालत', nextTitle:'{city} की अगली लोक अदालत', moreDates:'आगे की तारीख़ें',
  venue:'स्थान', reporting:'आपकी उपस्थिति', reportingVal:'ज़रूरी नहीं', bookingTitle:'इस कोर्ट में प्रक्रिया',
  carryTitle:'हमें आपसे क्या चाहिए — WhatsApp पर', carry:['वाहन RC की फ़ोटो','ड्राइविंग लाइसेंस की फ़ोटो','फ़ोटो ID — आधार या PAN','हस्ताक्षरित अधिकार-पत्र (हम तैयार करते हैं, आप सिर्फ़ साइन करें)'],
  addCal:'कैलेंडर में जोड़ें', reserveBtn:'मेरी जगह रिज़र्व करें', youPay:'आप देंगे (फ़्लैट 50%)', directions:'रास्ता देखें',
  faqEyebrow:'सवाल-जवाब', faqTitle:'लोग हमसे क्या पूछते हैं',
  faqs:[
   {q:'कौन-से चालान योग्य हैं?', a:'ज़्यादातर समझौता-योग्य ट्रैफ़िक अपराध — तेज़ गति, रेड लाइट जंप, बिना हेलमेट या सीटबेल्ट, गलत पार्किंग, दस्तावेज़ न होना — आमतौर पर लिए जाते हैं। शराब पीकर गाड़ी चलाना, दुर्घटना से जुड़े मामले और नियमित कोर्ट में भेजे जा चुके चालान आमतौर पर योग्य नहीं होते। आगे बढ़ने से पहले हम हर चालान की योग्यता पक्की करते हैं।'},
   {q:'क्या लोक अदालत का निपटारा अंतिम है?', a:'हाँ। लोक अदालत का अवॉर्ड अंतिम और बाध्यकारी होता है, इसके ख़िलाफ़ अपील नहीं होती। तय राशि जमा करने के बाद चालान निपटा हुआ माना जाता है।'},
   {q:'क्या मुझे खुद आना होगा?', a:'नहीं। जगह रिज़र्व करने के बाद हमारी टीम हस्ताक्षरित अधिकार-पत्र के साथ आपकी ओर से लोक अदालत जाती है। पत्र हम तैयार करते हैं — आप सिर्फ़ साइन करके WhatsApp पर भेजें।'},
   {q:'आपकी फ़ीस क्या है?', a:'चालान राशि का फ़्लैट 50%। चालान देखना मुफ़्त है और बुकिंग से पहले सही क़ीमत दिखती है। योग्यता पक्की होने तक कोई शुल्क नहीं।'},
   {q:'क्या यह सरकारी वेबसाइट है?', a:'नहीं। {brand} एक निजी सुविधा सेवा है। हमारा किसी सरकारी विभाग, अदालत या पुलिस प्राधिकरण से कोई संबंध नहीं है। आप चाहें तो सीधे लोक अदालत भी जा सकते हैं।'},
  ],
  disclaimerTitle:'अस्वीकरण', disclaimer:'हम एक निजी सुविधा सेवा हैं और किसी भी सरकारी विभाग, अदालत या पुलिस प्राधिकरण से संबद्ध नहीं हैं।',
  privacy:'गोपनीयता नीति', terms:'नियम और शर्तें', contact:'संपर्क', waFab:'WhatsApp',
  stepVerify:'सत्यापन', stepResults:'चालान', stepDetails:'बुकिंग',
  phoneTitle:'अपना मोबाइल नंबर सत्यापित करें', phoneDesc:'हम 6 अंकों का OTP भेजेंगे। चालान का विवरण सत्यापन के बाद ही दिखेगा।', phoneLabel:'मोबाइल नंबर', sendOtp:'OTP भेजें', phoneErr:'सही 10 अंकों का मोबाइल नंबर डालें', lookupConsent:'आगे बढ़कर आप हमें इस वाहन के ई-चालान रिकॉर्ड देखने की अनुमति देते हैं।',
  otpTitle:'6 अंकों का OTP डालें', otpDesc:'{phone} पर भेजा गया', change:'बदलें', resendIn:'{s} सेकंड में दोबारा भेजें', resend:'OTP दोबारा भेजें', verifyBtn:'सत्यापित करें और चालान देखें', otpDemo:'डेमो मोड: कोई भी 6 अंक', otpErr:'OTP गलत है या उसकी समय-सीमा ख़त्म हो गई। फिर कोशिश करें।', netErr:'कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।', tooMany:'बहुत ज़्यादा कोशिशें। कुछ मिनट रुकें।',
  loadingTitle:'चालान खोजे जा रहे हैं…', loadingDesc:'{plate} के ई-चालान रिकॉर्ड जाँचे जा रहे हैं',
  totalPending:'कुल पेंडिंग', challansFound:'{n} चालान मिले', eligibleSum:'{n} संभावित योग्य · {amt}', benchNote:'दिखाई गई योग्यता अनुमानित है। बुकिंग पक्की होने से पहले हम हर चालान जाँचते हैं।',
  tagEligible:'लोक अदालत के लिए संभावित योग्य', tagNot:'योग्य नहीं', tagPaid:'पहले ही भुगतान / निपटारा', settleCta:'मेरी लोक अदालत जगह रिज़र्व करें',
  emptyTitle:'कोई पेंडिंग चालान नहीं मिला 🎉', emptyDesc:'{plate} पर आज तक कोई पेंडिंग ई-चालान नहीं है।', alertTitle:'भविष्य के चालानों के अलर्ट पाएँ', alertDesc:'इस वाहन पर नया चालान आने पर हम WhatsApp करेंगे। मुफ़्त।', alertBtn:'WhatsApp अलर्ट चालू करें', checkAnother:'दूसरा वाहन देखें',
  errTitle:'अभी चालान रिकॉर्ड तक नहीं पहुँच पा रहे', errDesc:'चिंता न करें — अपना विवरण छोड़ें, हम खुद जाँचकर आपको कॉल करेंगे।',
  formTitle:'लोक अदालत में अपनी जगह रिज़र्व करें', formTitleErr:'हम खुद जाँचकर कॉल करेंगे', formSum:'{n} योग्य चालान ({amt}) · आप देंगे {fee}',
  fVehicle:'वाहन नंबर', fPhone:'मोबाइल नंबर', verified:'सत्यापित', fName:'पूरा नाम', fNamePh:'RC के अनुसार', fEmail:'ईमेल', optional:'(वैकल्पिक)', fType:'वाहन का प्रकार', car:'कार', bike:'दोपहिया', commercial:'कमर्शियल',
  consent:'मैं सहमत हूँ कि {brand} मेरे अनुरोध के लिए यह विवरण इस्तेमाल करे और मुझे WhatsApp पर अपडेट भेजे।', submit:'मेरे चालान जाँचें', feeNote:'अभी कोई भुगतान नहीं। योग्यता पक्की होने के बाद ही {fee} देना है। कोर्ट जाने की ज़रूरत नहीं।',
  thanksTitle:'अनुरोध मिल गया', thanksAlertTitle:'चालान अलर्ट चालू हैं', refLabel:'रेफ़रेंस नंबर', thanksWa:'हम 2 घंटे के अंदर आपको WhatsApp करेंगे।', thanksAlertWa:'नया चालान आने पर हम WhatsApp करेंगे।',
  nextTitle2:'आगे क्या होगा', next1:'एडवाइज़र आपके ई-चालान जाँचकर योग्य चालान और अंतिम क़ीमत बताएँगे', next2:'आगे बढ़ने पर RC, ID और हस्ताक्षरित अधिकार-पत्र WhatsApp पर भेजें', next3:'{date} को हमारी टीम निपटारा करेगी — रसीद WhatsApp पर',
  leadTitle:'अपने चालान जँचवाएँ', leadDesc:'अपना विवरण छोड़ें। हमारी टीम इस वाहन के सभी पेंडिंग ई-चालान जाँचकर योग्य राशि और क़ीमत WhatsApp पर बताएगी।', leadNote:'मुफ़्त। अभी कोई भुगतान नहीं। आगे बढ़ने का फ़ैसला करें तभी चालान राशि का 50% देना है।', dateTba:'तारीख़ जल्द घोषित होगी', dateTbaInline:'अगली लोक अदालत के दिन', dateTbaDesc:'अभी रिज़र्व करें, तारीख़ आते ही हम WhatsApp करेंगे।', waNow:'अभी WhatsApp पर बात करें', backHome:'होम पर वापस',
  reasonSerious:'गंभीर अपराध — लोक अदालत नहीं, नियमित कोर्ट में जाता है। फिर भी हम सलाह दे सकते हैं।', reasonCourt:'पहले ही नियमित कोर्ट भेजा जा चुका है — आमतौर पर लोक अदालत में नहीं लिया जाता। फिर भी हम सलाह दे सकते हैं।',
  sampleData:'नमूना डेटा · लाइव चालान API अभी जुड़ा नहीं है',
 }
};
